### ISSUE TITLE
change folder name from scripts to script

### ISSUE THREAD

**Issue by gannaramu** [aws-samples/iot-provisioning-secretfree#4]
the folder name was script in the repository but in the command, it was written scripts
![image](https://user-images.githubusercontent.com/12237488/91651211-260a2c80-ea47-11ea-98af-9781fef72504.png)
![image](https://user-images.githubusercontent.com/12237488/91651214-30c4c180-ea47-11ea-822a-6f634dd75335.png)

**Comment by rpcme** [comment]
Hi there - sorry for the late response. I accepted the pull request.
